# Generated by Django 3.2.4 on 2023-12-03 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='マニュアル名')),
            ],
            options={
                'verbose_name_plural': 'マニュアル',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=30, verbose_name='作業名')),
            ],
            options={
                'verbose_name_plural': '作業',
            },
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='手順名')),
                ('move', models.ManyToManyField(blank=True, related_name='previous_processes', to='internapp.Process', verbose_name='次の手順')),
                ('previous', models.ManyToManyField(blank=True, related_name='next_processes', to='internapp.Process', verbose_name='前の手順')),
                ('work_set', models.ManyToManyField(related_name='works_for_processes', to='internapp.Work', verbose_name='作業')),
            ],
            options={
                'verbose_name_plural': '手順',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=800, verbose_name='内容')),
                ('manual', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='internapp.manual', verbose_name='マニュアル')),
                ('process_set', models.ManyToManyField(related_name='documents', to='internapp.Process', verbose_name='手順')),
                ('relation', models.ManyToManyField(blank=True, related_name='related_documents', to='internapp.Manual', verbose_name='関連マニュアル')),
            ],
            options={
                'verbose_name_plural': 'ドキュメント',
            },
        ),
    ]
